name: Crave Download, Staticx Install and Upload to bashupload.com

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Download Crave Binary
        run: |
          curl -L -o crave-0.2-7064-linux-aarch64.bin https://github.com/accupara/crave/releases/download/0.2-7064/crave-0.2-7064-linux-aarch64.bin
          chmod +x crave-0.2-7064-linux-aarch64.bin

      - name: Install SCons
        run: sudo apt-get update && sudo apt-get install -y scons libxcrypt

      - name: Install staticx
        run: pip3 install staticx

      - name: Run staticx
        run: staticx ./crave-0.2-7064-linux-aarch64.bin ./crave-staticx.bin -l /lib/libcrypt.so.1

      - name: Upload to bashupload.com
        id: upload
        run: |
          curl -s -F "file=@crave-staticx.bin" https://bashupload.com
